services:

  # ------ CORE APPLICATION ----------
  app:
    build: .
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html/selaksa-app
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:           # <--- Tadi bagian ini hilang
        max-size: "10m"
        max-file: "3"

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: selaksa
      MYSQL_USER: selaksa
      MYSQL_PASSWORD: 313233
      MYSQL_ROOT_PASSWORD: root313233
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: selaksa
      PMA_PASSWORD: 313233
    depends_on:
      - mysql

  # --- Monitoring Tools ---
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    environment:
      - DOZZLE_USERNAME=admin
      - DOZZLE_PASSWORD=ganti_password_kamu_disini
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'

  # Monitor Log Host (Deploy & Nginx)
  log-monitor:
    image: alpine
    container_name: server_log_monitor
    volumes:
      - ./deploy.log:/logs/deploy.log:ro
      - /var/log/nginx/access.log:/logs/nginx-access.log:ro
      - /var/log/nginx/error.log:/logs/nginx-error.log:ro
    command: tail -f /logs/deploy.log /logs/nginx-access.log /logs/nginx-error.log
    restart: always

volumes:
  mysql_data:
