# CD dengan selh-hosted
name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    # perintah agar github mencari runner di laptop
    runs-on: self-hosted

    steps:
      - name: Jalankan Script Deploy Lokal
        run: |
          # masuk ke folder
          cd ~/prod_selaksa

          # Menjalankan script deploy
          chmod +x deploy.sh
          ./deploy.sh
