name: Laravel CI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies (no dev)
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Laravel basic check
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
